# Generated by Django 4.2.1 on 2023-06-11 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="network",
        ),
        migrations.AddField(
            model_name="game",
            name="networks",
            field=models.ManyToManyField(to="games.network"),
        ),
    ]
