# Generated by Django 4.2.7 on 2024-02-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0004_alter_game_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="conference",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="rank",
            field=models.IntegerField(null=True),
        ),
    ]
