# Generated by Django 4.2.7 on 2024-03-19 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0005_team_conference_team_rank"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="event",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
