# Generated by Django 4.2.7 on 2024-04-24 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0006_game_event"),
    ]

    operations = [
        migrations.CreateModel(
            name="WatchLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=200)),
                ("url", models.CharField(max_length=400)),
            ],
        ),
        migrations.AddField(
            model_name="game",
            name="watch_links",
            field=models.ManyToManyField(to="games.watchlink"),
        ),
    ]
